version: '3'

# All of these servers should have their ports exposed, but because we're using --scale we're not going to.
services:
  dfs-introducer:
    container_name: dfs-introducer
    environment:
      - INTRODUCER=1
      - SERVER=1
    ports:
      - "6002:6002"
      - "6003:6003"
    build: .

  worker:
    depends_on:
      - "dfs-introducer"
    environment:
      - SERVER=1
    build: .
