# Launches the entire ecosystem

FROM golang:alpine
RUN apk add --no-cache git
ENV CONFIG="/go/src/github.com/slin63/chord-dfs/config.json" \
    INTRODUCER=0 \
    GODIR="/go/src/github.com/slin63" \
    ALL=1

RUN mkdir -p /temp/store/

RUN git clone https://github.com/slin63/chord-failure-detector $GODIR/chord-failure-detector/
RUN git clone https://github.com/slin63/raft-consensus $GODIR/raft-consensus/

ADD . $GODIR/chord-dfs

RUN go build -o member $GODIR/chord-failure-detector/cmd/fd/main.go
RUN go build -o dfs $GODIR/chord-dfs/cmd/dfs/main.go
RUN go build -o raft $GODIR/raft-consensus/cmd/raft/main.go

CMD ["sh", "-c", "$GODIR/chord-dfs/scripts/init.sh"]

