version: '3'

# All of these servers should have their ports exposed, but because we're using --scale we're not going to.
services:
  introducer:
    container_name: introducer
    environment:
      - INTRODUCER=1
    ports:
      - "6002:6002"
      - "6003:6003"
      - "6004:6004"
    build:
      context: .
      dockerfile: dockerfiles/all/Dockerfile


  worker:
    depends_on:
      - "introducer"
    build:
      context: .
      dockerfile: dockerfiles/all/Dockerfile
