version: '3'

services:
  introducer:
    container_name: introducer
    environment:
      - INTRODUCER=1
    build:
      context: .
      dockerfile: dockerfiles/introducer/Dockerfile

  worker:
    depends_on:
      - "introducer"
    build:
      context: .
      dockerfile: dockerfiles/all/Dockerfile

networks:
  default:
    external:
      name: dfs-net
